# Use cpp as language as tests relay on build small projects
language: cpp

# Can test on one each of Linux/macOS because support is mainly
# across cmake versions (may need more as C++ standard support evolves)
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9
      compiler: clang

# At least on mac, should have suitable CMake via Homebrew, but want to upgrade
# to keep track of boost...
# On Linux, can grab CMake bundle, or use Docker, or use pullProducts
install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ] ; then
      brew update
      brew outdated cmake || brew upgrade cmake
    elif [ "$TRAVIS_OS_NAME" == "linux" ] ; then
      wget https://cmake.org/files/v3.9/cmake-3.9.3-Linux-x86_64.tar.gz
      tar -xf cmake-3.9.3-Linux-x86_64.tar.gz
      export PATH=$(pwd)/cmake-3.9.3-Linux-x86_64/bin:$PATH
    fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - ctest -VV

